export default {
	__all__: '',
	recall: 'Recall',
	process: 'Process',
	finalize: 'Finalize',
	submit: 'Submit',
	unrecall_to_submitted: 'Reinstate',
	unrecall_to_processing: 'Reinstate',
	unrecall_to_finalized: 'Reinstate',
	reporting_officer: 'Name of reporting officer',
	designation: 'Designation',
	organization: 'Organization',
	postal_code: 'Postal adddress',
	country: 'Country',
	phone: 'Phone',
	fax: 'Fax',
	email: 'E-mail',
	date: 'Date',
	subject: 'Subject'
}
