# Generated by Django 2.1.4 on 2019-10-02 13:12

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0204_auto_20190924_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
    ]
