# Generated by Django 2.0.5 on 2018-10-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article7export',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='article7export',
            name='quantity_exempted',
        ),
        migrations.RemoveField(
            model_name='article7export',
            name='type_exempted',
        ),
        migrations.RemoveField(
            model_name='article7import',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='article7import',
            name='quantity_exempted',
        ),
        migrations.RemoveField(
            model_name='article7import',
            name='type_exempted',
        ),
        migrations.RemoveField(
            model_name='article7production',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='article7production',
            name='quantity_exempted',
        ),
        migrations.RemoveField(
            model_name='article7production',
            name='type_exempted',
        ),
    ]
