# Generated by Django 2.0.5 on 2018-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180920_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('remark', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='remarks',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='remarks',
            new_name='remark',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='exemption',
            field=models.CharField(blank=True, choices=[('Critical use', 'CRITICAL'), ('Essential use', 'ESSENTIAL'), ('High ambient', 'HIGH_AMBIENT'), ('Process agent', 'PROCESS_AGENT'), ('Laboratory', 'LABORATORY'), ('Other', 'OTHER')], max_length=64),
        ),
    ]
