# Generated by Django 2.0.5 on 2018-10-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181018_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='trade_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Party'),
        ),
    ]
