# Generated by Django 2.0.5 on 2018-10-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181016_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article7export',
            name='destination_party',
            field=models.ForeignKey(default='thisisadummydefault', on_delete=django.db.models.deletion.PROTECT, related_name='article7exports_to', to='core.Party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article7import',
            name='source_party',
            field=models.ForeignKey(default='thisisadummydefault', on_delete=django.db.models.deletion.PROTECT, related_name='article7imports_from', to='core.Party'),
            preserve_default=False,
        ),
    ]
