# Generated by Django 2.0.5 on 2018-09-24 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180921_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='article7export',
            name='decision_cu',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7export',
            name='decision_eu',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7export',
            name='decision_hat',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7export',
            name='decision_lau',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7export',
            name='decision_pau',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7export',
            name='decision_qps',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7export',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party'),
        ),
        migrations.AddField(
            model_name='article7export',
            name='quantity_new_cu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7export',
            name='quantity_new_eu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7export',
            name='quantity_new_hat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7export',
            name='quantity_new_lau',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7export',
            name='quantity_new_pau',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7export',
            name='quantity_new_qps',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_cu',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_eu',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_hat',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_lau',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_pau',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_qps',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7import',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party'),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_new_cu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_new_eu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_new_hat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_new_lau',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_new_pau',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_new_qps',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
