# Generated by Django 2.0.5 on 2018-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181019_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
