# Generated by Django 2.1.4 on 2019-10-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_email_template_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingchannel',
            name='is_reserved_system',
            field=models.BooleanField(default=False),
        ),
    ]
