# Generated by Django 2.0.5 on 2018-09-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180924_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination_id', models.CharField(max_length=16, unique=True)),
                ('submit_date', models.DateField()),
                ('submit_amt', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ('nomination_id',),
            },
        ),
        migrations.CreateModel(
            name='PartyRatification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratification_id', models.CharField(max_length=16, unique=True)),
                ('ratification_type', models.CharField(blank=True, choices=[('Accession', 'ACCESSION'), ('Approval', 'APPROVAL'), ('Acceptance', 'ACCEPTANCE'), ('Ratification', 'RATIFICATION'), ('Succession', 'SUCCESSION'), ('Signing', 'SIGNING')], max_length=40)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('ratification_id',),
            },
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReportingObligationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('remark', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UsesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_type_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('decision_flag', models.BooleanField()),
                ('forms', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='partyhistory',
            name='is_article_5',
        ),
        migrations.AddField(
            model_name='party',
            name='ratification_date_kigali_amendment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='ratification_type_kigali_amendment',
            field=models.CharField(blank=True, choices=[('Accession', 'ACCESSION'), ('Approval', 'APPROVAL'), ('Acceptance', 'ACCEPTANCE'), ('Ratification', 'RATIFICATION'), ('Succession', 'SUCCESSION'), ('Signing', 'SIGNING')], max_length=40),
        ),
        migrations.AddField(
            model_name='partyhistory',
            name='is_hat',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='region',
            name='remark',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='subregion',
            name='remark',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='substance',
            name='gwp_error_plus_minus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='main_usage',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='substance',
            name='mp_control',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='substance',
            name='rcode',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SubmissionStatus'),
        ),
        migrations.AddField(
            model_name='partyratification',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratifications', to='core.Party'),
        ),
        migrations.AddField(
            model_name='partyratification',
            name='treaty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratifications', to='core.Treaty'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='core.Party'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='core.ReportingPeriod'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='substance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='uses_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='core.UsesType'),
        ),
        migrations.AddField(
            model_name='partyhistory',
            name='party_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PartyType'),
        ),
        migrations.AddField(
            model_name='submission',
            name='obligation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.ReportingObligationType'),
        ),
    ]
