# Generated by Django 2.1.4 on 2019-10-21 10:48

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191018_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=ozone.core.models.file.submission_file_upload_to),
        ),
    ]
