# Generated by Django 2.0.5 on 2018-10-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blend_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='composition',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
