# Generated by Django 2.0.5 on 2018-10-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181019_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretariat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Party'),
        ),
    ]
