# Generated by Django 2.0.5 on 2018-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180925_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partyratification',
            options={},
        ),
        migrations.RemoveField(
            model_name='article7export',
            name='party',
        ),
        migrations.RemoveField(
            model_name='article7import',
            name='party',
        ),
        migrations.RemoveField(
            model_name='partyratification',
            name='ratification_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='obligation_type',
        ),
        migrations.AddField(
            model_name='obligation',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='partyhistory',
            name='party_type',
            field=models.CharField(blank=True, choices=[('Article 5', 'A5'), ('Article 5 Group 1', 'A5G1'), ('Article 5 Group 2', 'A5G2'), ('Non Article 5', 'NA5')], max_length=40),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='PartyType',
        ),
        migrations.DeleteModel(
            name='ReportingObligationType',
        ),
        migrations.DeleteModel(
            name='SubmissionStatus',
        ),
    ]
