# Generated by Django 2.1.4 on 2019-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_illegal_trades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focalpoint',
            old_name='address',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='focalpoint',
            name='address',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='focalpoint',
            name='city',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='focalpoint',
            name='country',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
