# Generated by Django 2.0.5 on 2018-11-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181030_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partyhistory',
            options={'ordering': ('party', 'reporting_period'), 'verbose_name_plural': 'parties history'},
        ),
        migrations.AddField(
            model_name='partyhistory',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties_history', to='core.ReportingPeriod'),
        ),
        migrations.AlterUniqueTogether(
            name='partyhistory',
            unique_together={('party', 'reporting_period')},
        ),
        migrations.RemoveField(
            model_name='partyhistory',
            name='year',
        ),
    ]
