# Generated by Django 2.0.5 on 2018-10-05 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180926_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_new_cu',
            new_name='quantity_cu',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_new_eu',
            new_name='quantity_eu',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_new_hat',
            new_name='quantity_hat',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_new_lau',
            new_name='quantity_lau',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_new_pau',
            new_name='quantity_pau',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_new_qps',
            new_name='quantity_qps',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_new_cu',
            new_name='quantity_cu',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_new_eu',
            new_name='quantity_eu',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_new_hat',
            new_name='quantity_hat',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_new_lau',
            new_name='quantity_lau',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_new_pau',
            new_name='quantity_pau',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_new_qps',
            new_name='quantity_qps',
        ),
        migrations.AddField(
            model_name='article7production',
            name='decision_cu',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7production',
            name='decision_eu',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7production',
            name='decision_hat',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7production',
            name='decision_lau',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7production',
            name='decision_pau',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7production',
            name='decision_qps',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_cu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_eu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_hat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_lau',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_pau',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_qps',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
