# Generated by Django 2.0.5 on 2018-11-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_submission_cloned_from.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article7destruction',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article7destructions', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article7emissions', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article7exports', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article7imports', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article7nonpartytrades', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article7productions', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='highambienttemperatureimports', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='highambienttemperatureproductions', to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core.Submission'),
        ),
    ]
