# Generated by Django 2.1.4 on 2019-11-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_change_meta_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcons',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prodconsmt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
