# Generated by Django 2.1.4 on 2019-11-21 07:30

from django.conf import settings
from django.db import migrations
from django.utils.timezone import make_aware
from datetime import datetime, time
import pytz


def populate_prodcons_updated_at(apps, schema_editor):
    Submission = apps.get_model('core', 'Submission')
    ProdCons = apps.get_model('core', 'ProdCons')
    ProdConsMT = apps.get_model('core', 'ProdConsMT')

    timezone = pytz.timezone(settings.TIME_ZONE)

    # All objects will have the updated_at field set to the time the previous
    # migration (in which the updated_at field was added) was applied.
    for model in (ProdCons, ProdConsMT):
        for p in model.objects.values('id', 'submissions'):
            subs = p.get('submissions', {'art7': []})
            art7_subs = subs.get('art7', [])
            qs = model.objects.filter(id=p.get('id', None))
            if art7_subs:
                sub_id = art7_subs[0]
                sub = Submission.objects.filter(id=sub_id).first()
                if sub:
                    qs.update(
                        updated_at=make_aware(
                            datetime.combine(sub.submitted_at, time()),
                            timezone=timezone
                        )
                    )
                    continue
            qs.update(updated_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prodcons_updated_at'),
    ]

    operations = [
        migrations.RunPython(populate_prodcons_updated_at, reverse_code=migrations.RunPython.noop),
    ]
