# Generated by Django 2.0.5 on 2018-10-05 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181005_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_allowed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('consumption_allowed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('bdn_allowed', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Group')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='ExemptionApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_category', models.CharField(blank=True, max_length=256)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('emergency', models.BooleanField(default=False)),
                ('approved_teap_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('approved_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('approved_decision', models.CharField(blank=True, max_length=256)),
                ('lau_category', models.CharField(blank=True, max_length=256)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exemptionapproveds', to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
                ('uses_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UsesType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExemptionReported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_category', models.CharField(blank=True, max_length=256)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('quantity_exempted', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_produced', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_imported', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_open_bal', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_eu', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_exported', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_destroyed', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('import_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exemptionreporteds', to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
                ('uses_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UsesType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HATProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msac_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sdac_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dcpac_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remarks_party', models.CharField(blank=True, max_length=512)),
                ('remarks_os', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('consumption', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bdn_production', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Group')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAgentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, max_length=256)),
                ('counter', models.IntegerField()),
                ('application', models.CharField(max_length=256)),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('substance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAgentContainTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain_technology', models.CharField(max_length=512)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAgentEmitLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=256)),
                ('makeup_consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_emissions', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('P', 'Production'), ('C', 'Consumption')], max_length=1)),
                ('transferred_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('used_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_bdn', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('destination_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core.ReportingPeriod')),
                ('source_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='core.Party')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
            ],
        ),
        migrations.AddField(
            model_name='article7emission',
            name='quantity_destroyed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7emission',
            name='quantity_feedstock',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7emission',
            name='quantity_generated',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.CreateModel(
            name='HATImport',
            fields=[
                ('hatproduce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.HATProduce')),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Blend')),
                ('blend_hat_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.HATImport')),
            ],
            bases=('core.hatproduce',),
        ),
        migrations.AddField(
            model_name='hatproduce',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Submission'),
        ),
        migrations.AddField(
            model_name='hatproduce',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
    ]
