# Generated by Django 2.0.5 on 2018-10-08 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181005_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_allowed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('consumption_allowed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('basic_domestic_needs_allowed', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Group')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='ExemptionApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_uses_category', models.CharField(blank=True, max_length=256)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('emergency', models.BooleanField(default=False)),
                ('approved_teap_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('approved_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('approved_decision', models.CharField(blank=True, max_length=256)),
                ('laboratory_analytical_uses_category', models.CharField(blank=True, max_length=256)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exemptionapproveds', to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
                ('uses_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UsesType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExemptionReported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_uses_category', models.CharField(blank=True, max_length=256)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('quantity_exempted', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_produced', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_imported', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_open_bal', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('essential_uses_quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_exported', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_destroyed', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('import_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exemptionreporteds', to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
                ('uses_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UsesType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighAmbientTemperatureImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_split_air_conditioners_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('split_ducted_air_conditioners_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ducted_commercial_packaged_air_conditioners_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remarks_party', models.CharField(blank=True, max_length=512)),
                ('remarks_os', models.CharField(blank=True, max_length=512)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Blend')),
                ('blend_high_ambient_temperature_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.HighAmbientTemperatureImport')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Submission')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighAmbientTemperatureProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_split_air_conditioners_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('split_ducted_air_conditioners_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ducted_commercial_packaged_air_conditioners_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remarks_party', models.CharField(blank=True, max_length=512)),
                ('remarks_os', models.CharField(blank=True, max_length=512)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Submission')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('consumption', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('basic_domestic_needs_production', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Group')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAgentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, max_length=256)),
                ('counter', models.IntegerField()),
                ('application', models.CharField(max_length=256)),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('substance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAgentContainTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain_technology', models.CharField(max_length=512)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAgentEmitLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=256)),
                ('makeup_consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_emissions', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('P', 'Production'), ('C', 'Consumption')], max_length=1)),
                ('transferred_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('used_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_basic_domestic_need', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('destination_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core.ReportingPeriod')),
                ('source_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='core.Party')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
            ],
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='decision_cu',
            new_name='critical_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_cu',
            new_name='critical_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='decision_eu',
            new_name='essential_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_eu',
            new_name='essential_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='decision_hat',
            new_name='high_ambient_temperature_decision',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_hat',
            new_name='high_ambient_temperature_quantity',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='decision_lau',
            new_name='laboratory_analytical_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_lau',
            new_name='laboratory_analytical_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='decision_pau',
            new_name='process_agent_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_pau',
            new_name='process_agent_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='decision_qps',
            new_name='quarantine_pre_shipment_decision',
        ),
        migrations.RenameField(
            model_name='article7export',
            old_name='quantity_qps',
            new_name='quarantine_pre_shipment_quantity',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='decision_cu',
            new_name='critical_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_cu',
            new_name='critical_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='decision_eu',
            new_name='essential_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_eu',
            new_name='essential_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='decision_hat',
            new_name='high_ambient_temperature_decision',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_hat',
            new_name='high_ambient_temperature_quantity',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='decision_lau',
            new_name='laboratory_analytical_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_lau',
            new_name='laboratory_analytical_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='decision_pau',
            new_name='process_agent_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_pau',
            new_name='process_agent_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='decision_qps',
            new_name='quarantine_pre_shipment_decision',
        ),
        migrations.RenameField(
            model_name='article7import',
            old_name='quantity_qps',
            new_name='quarantine_pre_shipment_quantity',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='decision_cu',
            new_name='critical_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='quantity_cu',
            new_name='critical_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='decision_eu',
            new_name='essential_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='quantity_eu',
            new_name='essential_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='decision_hat',
            new_name='high_ambient_temperature_decision',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='quantity_hat',
            new_name='high_ambient_temperature_quantity',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='decision_lau',
            new_name='laboratory_analytical_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='quantity_lau',
            new_name='laboratory_analytical_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='decision_pau',
            new_name='process_agent_uses_decision',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='quantity_pau',
            new_name='process_agent_uses_quantity',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='decision_qps',
            new_name='quarantine_pre_shipment_decision',
        ),
        migrations.RenameField(
            model_name='article7production',
            old_name='quantity_qps',
            new_name='quarantine_pre_shipment_quantity',
        ),
        migrations.RenameField(
            model_name='partyhistory',
            old_name='is_hat',
            new_name='is_high_ambient_temperature',
        ),
        migrations.AddField(
            model_name='article7emission',
            name='quantity_destroyed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7emission',
            name='quantity_feedstock',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7emission',
            name='quantity_generated',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
