# Generated by Django 2.0.5 on 2018-11-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181120_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obligation',
            old_name='is_continuous',
            new_name='has_reporting_periods',
        ),
    ]
