# Generated by Django 2.1.4 on 2019-12-05 10:27

from django.core.management import call_command
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_populate_prodcons_mt_flags'),
    ]

    def loadfixtures(apps, schema_editor):
        call_command('loaddata', 'data/fixtures/reporting_channels.json'),

    operations = [
        migrations.RemoveField(
            model_name='reportingchannel',
            name='is_reserved_system',
        ),
        migrations.AddField(
            model_name='reportingchannel',
            name='is_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportingchannel',
            name='is_secretariat',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            loadfixtures,
            reverse_code=lambda apps, schema_editor:None
        ),
    ]
