# Generated by Django 2.1.4 on 2019-12-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reporting_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingchannel',
            name='is_default_for_cloning',
        ),
    ]
