# Generated by Django 2.0.5 on 2018-10-10 11:22

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20181009_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transition', models.CharField(max_length=60)),
                ('from_state', models.CharField(max_length=60)),
                ('to_state', models.CharField(max_length=60)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'verbose_name': 'workflow event',
            },
        ),
        migrations.RenameField(
            model_name='highambienttemperatureimport',
            old_name='quantity_ducted_commercial_packaged_air_conditioners_produced',
            new_name='quantity_dcpac_produced',
        ),
        migrations.RenameField(
            model_name='highambienttemperatureimport',
            old_name='quantity_multi_split_air_conditioners_produced',
            new_name='quantity_msac_produced',
        ),
        migrations.RenameField(
            model_name='highambienttemperatureimport',
            old_name='quantity_split_ducted_air_conditioners_produced',
            new_name='quantity_sdac_produced',
        ),
        migrations.RenameField(
            model_name='highambienttemperatureproduce',
            old_name='quantity_ducted_commercial_packaged_air_conditioners_produced',
            new_name='quantity_dcpac_produced',
        ),
        migrations.RenameField(
            model_name='highambienttemperatureproduce',
            old_name='quantity_multi_split_air_conditioners_produced',
            new_name='quantity_msac_produced',
        ),
        migrations.RenameField(
            model_name='highambienttemperatureproduce',
            old_name='quantity_split_ducted_air_conditioners_produced',
            new_name='quantity_sdac_produced',
        ),
        migrations.RenameField(
            model_name='substance',
            old_name='rcode',
            new_name='r_code',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='submission',
            name='_current_state',
            field=models.CharField(blank=True, db_column='current_state', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='_previous_state',
            field=models.CharField(blank=True, db_column='previous_state', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated')], db_column='workflow_class', default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='processagentapplication',
            name='counter',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_valid',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='transitionevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_events', to='core.Submission'),
        ),
        migrations.AddField(
            model_name='transitionevent',
            name='triggered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='transitionevent',
            unique_together={('timestamp', 'submission', 'from_state', 'to_state')},
        ),
    ]
