# Generated by Django 2.0.5 on 2018-11-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicalsubmission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transitionevent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transitionevent',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='transitionevent',
            name='triggered_by',
        ),
        migrations.DeleteModel(
            name='TransitionEvent',
        ),
    ]
