# Generated by Django 2.0.5 on 2018-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_substance_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendcomponent',
            name='cnumber',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='blendcomponent',
            name='component_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
