# Generated by Django 2.0.5 on 2018-10-10 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181010_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighAmbientTemperatureProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks_party', models.CharField(blank=True, max_length=512)),
                ('remarks_os', models.CharField(blank=True, max_length=512)),
                ('quantity_msac_produced', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_sdac_produced', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_dcpac_produced', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highambienttemperatureproductions', to='core.Submission')),
                ('substance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='highambienttemperatureproduce',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='highambienttemperatureproduce',
            name='substance',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='source_party',
        ),
        migrations.AddField(
            model_name='transfer',
            name='remarks_os',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='transfer',
            name='remarks_party',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='transfer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.Submission'),
        ),
        migrations.DeleteModel(
            name='HighAmbientTemperatureProduce',
        ),
    ]
