# Generated by Django 2.0.5 on 2018-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181122_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='article7destruction',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article7emission',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article7export',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article7import',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article7nonpartytrade',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article7production',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article7questionnaire',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highambienttemperatureimport',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highambienttemperatureproduction',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer',
            name='ordering_id',
            field=models.IntegerField(default=0),
        ),
    ]
