# Generated by Django 2.0.5 on 2018-11-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181122_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='form_type',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
