# Generated by Django 2.1.4 on 2019-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191206_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafreportusecategory',
            name='remarks',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
