# Generated by Django 2.0.5 on 2018-10-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181010_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='source_party',
            new_name='party',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='remark',
        ),
        migrations.AddField(
            model_name='transfer',
            name='remarks_os',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='transfer',
            name='remarks_party',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='transfer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.Submission'),
        ),
    ]
