# Generated by Django 2.0.5 on 2018-10-12 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181010_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAgentEmissionLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=256)),
                ('makeup_consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_emissions', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remark', models.CharField(blank=True, max_length=512)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_agent_emission_limits', to='core.Party')),
            ],
        ),
        migrations.RemoveField(
            model_name='processagentemitlimit',
            name='party',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='submit_amt',
        ),
        migrations.AddField(
            model_name='nomination',
            name='submit_amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article7production',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_measures', to='core.Group'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_measures', to='core.Party'),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_measures', to='core.ReportingPeriod'),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_dcpac_produced',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_msac_produced',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_sdac_produced',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_dcpac_produced',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_msac_produced',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_sdac_produced',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='core.Group'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='core.Party'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='core.ReportingPeriod'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='processagentapplication',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.DeleteModel(
            name='ProcessAgentEmitLimit',
        ),
    ]
