# Generated by Django 2.0.5 on 2018-10-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181010_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='party',
        ),
    ]
