# Generated by Django 2.0.5 on 2018-11-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_obligation_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blend',
            name='custom',
        ),
        migrations.AddField(
            model_name='blend',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_blends', to='core.Party'),
        ),
    ]
