# Generated by Django 2.0.5 on 2018-11-26 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181126_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='article7export',
            name='decision_other_uses',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7export',
            name='quantity_other_uses',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_other_uses',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_other_uses',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7production',
            name='decision_other_uses',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_for_destruction',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7production',
            name='quantity_other_uses',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
