# Generated by Django 2.0.5 on 2018-11-27 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_make_substance_blankable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article7export',
            name='destination_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article7exports_to', to='core.Party'),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='source_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article7imports_from', to='core.Party'),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='trade_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party'),
        ),
    ]
