# Generated by Django 2.0.5 on 2018-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_src_dst_parties_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='is_reporting_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='is_reporting_open',
            field=models.BooleanField(default=False),
        ),
    ]
