# Generated by Django 2.0.5 on 2018-11-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181127_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substance',
            name='annex',
        ),
        migrations.AlterField(
            model_name='substance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substances', to='core.Group'),
        ),
    ]
