# Generated by Django 2.0.5 on 2018-11-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_make_group_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article7questionnaire',
            name='ordering_id',
        ),
    ]
