# Generated by Django 2.0.5 on 2018-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_article7questionnaire_ordering_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='designation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='fax',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='organization',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='postal_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='reporting_officer',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='submission',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='designation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='fax',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='submission',
            name='organization',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='submission',
            name='phone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='submission',
            name='postal_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='reporting_officer',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
