# Generated by Django 2.0.5 on 2018-11-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181129_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingperiod',
            name='is_year',
        ),
    ]
