# Generated by Django 2.0.5 on 2018-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181129_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_read_only',
            field=models.BooleanField(default=True),
        ),
    ]
