# Generated by Django 2.0.5 on 2018-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20181204_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_read_only',
            field=models.BooleanField(default=True),
        ),
    ]
