# Generated by Django 2.0.5 on 2018-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_user_is_read_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='type',
            field=models.CharField(choices=[('Zeotrope', 'ZEOTROPE'), ('Azeotrope', 'AZEOTROPE'), ('Methyl bromide', 'MeBr'), ('Other', 'OTHER')], max_length=128),
        ),
    ]
