# Generated by Django 2.0.5 on 2018-12-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20181206_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='ratification_date_beijing_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_date_copenhagen_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_date_kigali_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_date_london_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_date_montreal_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_date_montreal_protocol',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_date_vienna_convention',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_type_beijing_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_type_copenhagen_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_type_kigali_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_type_london_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_type_montreal_amendment',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_type_montreal_protocol',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ratification_type_vienna_convention',
        ),
        migrations.RemoveField(
            model_name='party',
            name='signed_montreal_protocol',
        ),
        migrations.RemoveField(
            model_name='party',
            name='signed_vienna_convention',
        ),
    ]
