# Generated by Django 2.0.5 on 2018-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20181207_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
    ]
