# Generated by Django 2.0.5 on 2018-12-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20181210_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='is_contained_in_polyols',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
