# Generated by Django 2.0.5 on 2018-12-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20181211_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='partyhistory',
            name='is_article5',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partyhistory',
            name='party_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_histories', to='core.PartyType'),
        ),
        migrations.AlterField(
            model_name='partyhistory',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_histories', to='core.ReportingPeriod'),
        ),
    ]
