# Generated by Django 2.0.5 on 2018-12-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_obligations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_officer', models.CharField(blank=True, max_length=256)),
                ('designation', models.CharField(blank=True, max_length=256)),
                ('organization', models.CharField(blank=True, max_length=256)),
                ('postal_code', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=128)),
                ('fax', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='reporting_officer',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='country',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='reporting_officer',
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='info',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.SubmissionInfo'),
        ),
        migrations.AddField(
            model_name='submission',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='core.SubmissionInfo'),
        ),
    ]
