# Generated by Django 2.0.5 on 2018-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20181211_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='submitted_via',
            field=models.CharField(choices=[('Web form', 'WEBFORM'), ('Email', 'EMAIL'), ('Legacy', 'LEGACY')], max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_via',
            field=models.CharField(choices=[('Web form', 'WEBFORM'), ('Email', 'EMAIL'), ('Legacy', 'LEGACY')], max_length=32),
        ),
    ]
