# Generated by Django 2.0.5 on 2018-12-13 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20181212_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='article7export',
            name='quantity_polyols',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='article7import',
            name='quantity_polyols',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
