# Generated by Django 2.0.5 on 2018-12-14 13:38

from django.db import migrations
from django.core.management import call_command


def remove_unk_and_czs(apps, schema_editor):
    Party = apps.get_model('core', 'Party')
    for party in Party.objects.filter(abbr__in=["UNK", "CZS"]):
        party.history.all().delete()
        party.ratifications.all().delete()
        party.delete()


def refresh_fixtures(apps, schema_editor):
    if not apps.get_model('core', 'Party').objects.count():
        # Nothing to refresh.
        return
    call_command('loaddata', 'parties')
    call_command('loaddata', 'partieshistory')
    call_command('loaddata', 'partiesratification')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_quantity_polyols'),
    ]

    operations = [
        migrations.RunPython(remove_unk_and_czs, elidable=True),
        migrations.RunPython(refresh_fixtures, elidable=True),
    ]
