# Generated by Django 2.0.5 on 2018-12-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_unk_and_czs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='trade_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Party'),
        ),
    ]
