# Generated by Django 2.0.5 on 2018-12-18 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20181217_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article7destruction',
            name='quantity_destroyed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
