# Generated by Django 2.0.5 on 2018-12-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20181218_1343'),
        ('core', '0042_more_flags'),
    ]

    operations = [
    ]
