# Generated by Django 2.0.5 on 2018-12-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_submission_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article7flags',
            name='annex',
        ),
        migrations.RemoveField(
            model_name='article7flags',
            name='group',
        ),
        migrations.RemoveField(
            model_name='article7flags',
            name='submission',
        ),
        migrations.DeleteModel(
            name='Article7Flags',
        ),
    ]
