# Generated by Django 2.0.5 on 2018-12-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20181221_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='filled_by_secretariat',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='filled_by_secretariat',
        ),
    ]
