# Generated by Django 2.1.4 on 2019-01-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_filled_by_secretariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='destruction_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='destruction_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='emissions_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='emissions_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='exports_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='exports_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='imports_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='imports_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='nonparty_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='nonparty_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='production_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='production_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='destruction_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='destruction_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='emissions_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='emissions_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='exports_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='exports_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='imports_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='imports_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='nonparty_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='nonparty_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='production_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='production_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
