# Generated by Django 2.1.4 on 2019-01-07 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ozone.core.models.data
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20190103_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ozone.core.models.file.File.get_storage_directory)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='core.Submission')),
            ],
            options={
                'abstract': False,
            },
            bases=(ozone.core.models.data.ModifyPreventionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UploadToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=ozone.core.models.file.default_token, max_length=100, unique=True)),
                ('filename', models.CharField(max_length=256)),
                ('tus_id', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=ozone.core.models.file.token_valid_until)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tokens', to='core.Submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_upload_token',
                'ordering': ('-created_at',),
            },
        ),
    ]
