# Generated by Django 2.1.4 on 2019-01-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_submissionfile_uploadtoken'),
        ('core', '0050_auto_20190107_1414'),
    ]

    operations = [
    ]
