# Generated by Django 2.1.4 on 2019-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20190107_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='hat_imports_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='hat_imports_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='hat_imports_remarks_party',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='hat_imports_remarks_secretariat',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
