# Generated by Django 2.1.4 on 2019-01-08 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20190107_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='info',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='info',
        ),
        migrations.AddField(
            model_name='submissioninfo',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='core.Submission'),
        ),
    ]
