# Generated by Django 2.1.4 on 2019-01-08 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_submission_info_oentoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article7destruction',
            name='blend',
            field=models.ForeignKey(blank=True, help_text='Blend ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Blend'),
        ),
        migrations.AlterField(
            model_name='article7destruction',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='article7destruction',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7destruction',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7destruction',
            name='substance',
            field=models.ForeignKey(blank=True, help_text='Substance ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='blend',
            field=models.ForeignKey(blank=True, help_text='Blend ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Blend'),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='substance',
            field=models.ForeignKey(blank=True, help_text='Substance ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='blend',
            field=models.ForeignKey(blank=True, help_text='Blend ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Blend'),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='substance',
            field=models.ForeignKey(blank=True, help_text='Substance ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='blend',
            field=models.ForeignKey(blank=True, help_text='Blend ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Blend'),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='substance',
            field=models.ForeignKey(blank=True, help_text='Substance ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='blend',
            field=models.ForeignKey(blank=True, help_text='Blend ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Blend'),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_dcpac',
            field=models.FloatField(blank=True, help_text='Used in ducted commercial packaged air conditioners', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_msac',
            field=models.FloatField(blank=True, help_text='Used in multi-split air conditioners', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_sdac',
            field=models.FloatField(blank=True, help_text='Used in split ducted air conditioners', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='substance',
            field=models.ForeignKey(blank=True, help_text='Substance ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Substance'),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_dcpac',
            field=models.FloatField(blank=True, help_text='Used in ducted commercial packaged air conditioners', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_msac',
            field=models.FloatField(blank=True, help_text='Used in multi-split air conditioners', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_sdac',
            field=models.FloatField(blank=True, help_text='Used in split ducted air conditioners', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='destruction_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for destruction', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='destruction_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for destruction', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='emissions_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for emissions', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='emissions_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for emissions', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='exports_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for exports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='exports_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for exports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='hat_imports_remarks_party',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the reporting party for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='hat_imports_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the ozone secretariat for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='hat_production_remarks_party',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the reporting party for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='hat_production_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the ozone secretariat for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='imports_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='imports_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='nonparty_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for nonparty', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='nonparty_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for nonparty', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='production_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='production_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='destruction_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for destruction', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='destruction_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for destruction', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='emissions_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for emissions', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='emissions_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for emissions', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exports_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for exports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exports_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for exports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hat_imports_remarks_party',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the reporting party for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hat_imports_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the ozone secretariat for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hat_production_remarks_party',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the reporting party for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hat_production_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General HAT obligation remarks added by the ozone secretariat for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='imports_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='imports_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for imports', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nonparty_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for nonparty', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nonparty_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for nonparty', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='production_remarks_party',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the reporting party for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='production_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Article7 obligation remarks added by the ozone secretariat for production', max_length=9999),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='ordering_id',
            field=models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='remarks_os',
            field=models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='remarks_party',
            field=models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999),
        ),
    ]
