# Generated by Django 2.1.4 on 2019-01-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissioninfo',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='core.Submission'),
        ),
    ]
