# Generated by Django 2.1.4 on 2019-01-09 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_submission_info_non_nullable_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='name',
            field=models.CharField(max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
    ]
