# Generated by Django 2.1.4 on 2019-01-10 11:26

from django.db import migrations, models
import django.db.models.deletion
import ozone.core.models.file
import ozone.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20190109_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks_party', models.CharField(blank=True, help_text='Remarks added by the reporting party', max_length=9999)),
                ('remarks_os', models.CharField(blank=True, help_text='Remarks added by the ozone secretariat', max_length=9999)),
                ('ordering_id', models.IntegerField(default=0, help_text='This allows the interface to keep the data entries in their original order, as given by the user.')),
            ],
            options={
                'abstract': False,
            },
            bases=(ozone.core.models.reporting.ModifyPreventionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OtherSubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='dataother',
            name='other_submission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_other', to='core.OtherSubmissionType'),
        ),
        migrations.AddField(
            model_name='dataother',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataothers', to='core.Submission'),
        ),
    ]
