# Generated by Django 2.1.4 on 2019-01-14 13:45

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20190110_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataother',
            name='other_submission_type',
        ),
        migrations.AddField(
            model_name='obligation',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OtherSubmissionType',
        ),
    ]
