# Generated by Django 2.1.4 on 2019-01-15 13:07

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_obligations'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='tus_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='upload_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
    ]
