# Generated by Django 2.1.4 on 2019-01-16 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_tus_id_in_file_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
        migrations.AlterField(
            model_name='user',
            name='party',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(parent_party_id=django.db.models.expressions.F('id')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Party'),
        ),
    ]
