# Generated by Django 2.1.4 on 2019-01-16 09:50

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20190115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='type',
            field=models.CharField(choices=[('Zeotrope', 'ZEOTROPE'), ('Azeotrope', 'AZEOTROPE'), ('Methyl bromide', 'MeBr'), ('Other', 'OTHER'), ('Custom', 'CUSTOM')], max_length=128),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
    ]
