# Generated by Django 2.1.4 on 2019-01-18 12:07

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20190117_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='gwp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blend',
            name='odp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
