# Generated by Django 2.1.4 on 2019-01-23 17:07

from django.db import migrations, models
import ozone.core.models.file

DATA = (
    ("A", "ar"),
    ("C", "zh"),
    ("E", "en"),
    ("F", "fr"),
    ("R", "ru"),
    ("S", "es"),
)


def add_language_codes(apps, schema_editor):
    Language = apps.get_model('core', 'Language')
    for language_id, iso in DATA:
        Language.objects.filter(language_id=language_id).update(iso=iso)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20190123_1635'),
    ]

    # Can't be done in a single operation, so do a 3 step:
    #  - add the column first while permitting it to be null
    #  - fill in with data
    #  - make unique
    operations = [
        migrations.AddField(
            model_name='language',
            name='iso',
            field=models.CharField(max_length=5, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_language_codes, elidable=True),
        migrations.AlterField(
            model_name='language',
            name='iso',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
