# Generated by Django 2.1.4 on 2019-01-24 16:34

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20190123_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blend',
            name='mp_control',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='mp_control',
        ),
    ]
