# Generated by Django 2.1.4 on 2019-02-05 11:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20190201_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemptionapproved',
            name='flag_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption')], db_column='workflow_class', default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption')], db_column='workflow_class', default='empty', max_length=32),
        ),
    ]
