# Generated by Django 2.1.4 on 2019-02-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20190205_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemptionapproved',
            name='flag_approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
