# Generated by Django 2.1.4 on 2019-02-08 10:23

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_raf_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='raf_remarks_party',
            field=models.CharField(blank=True, help_text='General RAF remarks added by the reporting party', max_length=9999),
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='raf_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General RAF remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='raf_remarks_party',
            field=models.CharField(blank=True, help_text='General RAF remarks added by the reporting party', max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='raf_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General RAF remarks added by the ozone secretariat', max_length=9999),
        ),
    ]
