# Generated by Django 2.1.4 on 2019-02-11 09:43

from django.db import migrations, models
import django.db.models.deletion
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20190208_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafimport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='core.RAFReport'),
        ),
    ]
