# Generated by Django 2.1.4 on 2019-02-11 13:09

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20190211_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='exemptions_nomination_remarks_os',
            new_name='exemption_nomination_remarks_os',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='exemptions_nomination_remarks_os',
            new_name='exemption_nomination_remarks_os',
        ),
    ]
