# Generated by Django 2.1.4 on 2019-02-11 13:39

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_exemption_nomination_typo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='exemption_approved_remarks_os',
            new_name='exemption_approved_remarks_secretariat',
        ),
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='exemption_nomination_remarks_os',
            new_name='exemption_nomination_remarks_secretariat',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='exemption_approved_remarks_os',
            new_name='exemption_approved_remarks_secretariat',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='exemption_nomination_remarks_os',
            new_name='exemption_nomination_remarks_secretariat',
        ),
    ]
