# Generated by Django 2.1.4 on 2019-02-13 08:00

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_fax_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioninfo',
            name='postal_address',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
