# Generated by Django 2.1.4 on 2019-02-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_adding_postal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='submitted_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateField(null=True),
        ),
    ]
