# Generated by Django 2.1.4 on 2019-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_adding_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioninfo',
            name='submission_format',
            field=models.CharField(blank=True, choices=[('A7 Data forms', 'A7_DATA_FORMS'), ('Annex to data form 1', 'ANNEX_TO_DATA_FORM_1'), ('Country Programme data', 'COUNTRY_PROGRAMME_DATA'), ('Email', 'EMAIL'), ('Letter', 'LETTER'), ('Questionnaire', 'QUESTIONNAIRE')], help_text='This field describes type of submission.', max_length=128),
        )
    ]
