# Generated by Django 2.1.4 on 2019-02-19 07:45

from django.db import migrations, models


def move_postal_code_to_address(apps, schema_editor):
    SubmissionInfo = apps.get_model('core', 'SubmissionInfo')
    SubmissionInfo.objects.filter(
        postal_code__isnull=False
    ).exclude(
        postal_code=''
    ).update(
        postal_address=models.F('postal_code')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_adding_postal_address'),
    ]

    operations = [
        migrations.RunPython(move_postal_code_to_address, elidable=True),
        migrations.RemoveField(
            model_name='submissioninfo',
            name='postal_code',
        ),
    ]
