# Generated by Django 2.1.4 on 2019-02-19 13:24

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20190219_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='submitted_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateField(null=True),
        ),
    ]
