# Generated by Django 2.1.4 on 2019-02-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='is_default',
            field=models.NullBooleanField(default=None, help_text="If set to true it means that the current obligation is used as default for 'Data entry submissions' and 'All submissions' sections."),
        ),
    ]
