# Generated by Django 2.1.4 on 2019-02-25 09:39

from django.db import migrations, models
from django.core.management import call_command
from django.core.serializers import base, python
import django.db.models.deletion


def load_essen_crit_types(apps, schme_editor):
    old_get_model = python._get_model

    def _get_model(model_identifier):
        try:
            return apps.get_model(model_identifier)
        except (LookupError, TypeError):
            raise base.DeserializationError(
                "Invalid model identifier: '%s'" % model_identifier)

    python._get_model = _get_model

    try:
        call_command('loaddata', 'essen_crit_types_old')
    finally:
        python._get_model = old_get_model


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20190220_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAFTypeOfUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'raf_type_of_use',
            },
        ),
        migrations.AddField(
            model_name='rafreport',
            name='type_of_use',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.RAFTypeOfUse'),
        ),
        migrations.RunPython(load_essen_crit_types),
    ]
