# Generated by Django 2.1.4 on 2019-02-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20190225_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafimport',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Party'),
        ),
    ]
