# Generated by Django 2.1.4 on 2019-03-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20190226_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RAFTypeOfUse',
            new_name='EssentialCriticalType',
        ),
        migrations.RenameField(
            model_name='rafreport',
            old_name='type_of_use',
            new_name='essen_crit_type',
        ),
        migrations.AlterModelTable(
            name='essentialcriticaltype',
            table='essen_crit_type',
        ),
    ]
