# Generated by Django 2.1.4 on 2019-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20190301_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemptionreported',
            name='import_party',
        ),
        migrations.RemoveField(
            model_name='exemptionreported',
            name='substance',
        ),
        migrations.DeleteModel(
            name='ExemptionReported',
        ),
    ]
