# Generated by Django 2.1.4 on 2019-03-12 08:57

from django.db import migrations, models
from django.core.management import call_command

def refresh_reporting_channels(apps, schema_editor):
        call_command('loaddata', 'reporting_channels')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20190311_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingchannel',
            name='is_default_for_cloning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportingchannel',
            name='is_default_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportingchannel',
            name='is_default_secretariat',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(refresh_reporting_channels),
    ]
