# Generated by Django 2.1.4 on 2019-03-12 08:57

from django.db import migrations, models


def update_reporting_channels(apps, schema_editor):
    ReportingChannel = apps.get_model('core', 'ReportingChannel')
    ReportingChannel.objects.filter(name="Web form").update(
        is_default_for_cloning=True,
        is_default_party=True,
        is_default_secretariat=False
    )
    ReportingChannel.objects.filter(name="Email").update(
        is_default_for_cloning=False,
        is_default_party=False,
        is_default_secretariat=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20190311_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingchannel',
            name='is_default_for_cloning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportingchannel',
            name='is_default_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportingchannel',
            name='is_default_secretariat',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_reporting_channels),
    ]
