# Generated by Django 2.1.4 on 2019-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_reporting_channel_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='remarks_party',
        ),
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='remarks_secretariat',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='remarks_party',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='remarks_secretariat',
        ),
    ]
