# Generated by Django 2.1.4 on 2019-03-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_remove_questionnaire_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article7questionnaire',
            name='has_destroyed',
            field=models.NullBooleanField(help_text='If set to true it allows to complete destructions data form.'),
        ),
        migrations.AlterField(
            model_name='article7questionnaire',
            name='has_emissions',
            field=models.NullBooleanField(help_text='If set to true it allows to complete emissions data form.'),
        ),
        migrations.AlterField(
            model_name='article7questionnaire',
            name='has_exports',
            field=models.NullBooleanField(help_text='If set to true it allows to complete exports data form.'),
        ),
        migrations.AlterField(
            model_name='article7questionnaire',
            name='has_imports',
            field=models.NullBooleanField(help_text='If set to true it allows to complete imports data form.'),
        ),
        migrations.AlterField(
            model_name='article7questionnaire',
            name='has_nonparty',
            field=models.NullBooleanField(help_text='If set to true it allows to complete non-party trades data form.'),
        ),
        migrations.AlterField(
            model_name='article7questionnaire',
            name='has_produced',
            field=models.NullBooleanField(help_text='If set to true it allows to complete productions data form.'),
        ),
    ]
