# Generated by Django 2.1.4 on 2019-03-21 07:42

from django.db import migrations, models
import django.db.models.deletion
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_nullable_questionnaire_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Language'),
        ),
    ]
