# Generated by Django 2.1.4 on 2019-03-22 14:36

from django.db import migrations


def set_language(apps, schema_editor):
    Language = apps.get_model('core', 'Language')
    User = apps.get_model('core', 'User')

    # first() will return None if no language found (e.g. unit tests)
    en = Language.objects.filter(iso='en').first()
    for user in User.objects.all():
        user.language = en
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_default_language'),
    ]

    operations = [
        migrations.RunPython(set_language),
    ]
