# Generated by Django 2.1.4 on 2019-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_make_language_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend',
            name='legacy_blend_id',
            field=models.IntegerField(blank=True, help_text='Used by data import management command, for reports that contain blends, instead of substances.', null=True, unique=True),
        ),
    ]
