# Generated by Django 2.1.4 on 2019-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20190326_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyratification',
            name='entry_into_force_date',
            field=models.DateField(blank=True),
        ),
    ]
