# Generated by Django 2.1.4 on 2019-03-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20190327_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyratification',
            name='entry_into_force_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
