# Generated by Django 2.1.4 on 2019-03-29 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20190328_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Baseline types can be A5/NA5 Prod/Cons, BDN_pre2k or BDN', max_length=64)),
                ('remarks', models.CharField(blank=True, help_text='Remarks for this baseline type', max_length=9999)),
            ],
            options={
                'db_table': 'baseline_type',
            },
        ),
        migrations.RenameField(
            model_name='controlmeasure',
            old_name='consumption_allowed',
            new_name='allowed',
        ),
        migrations.RenameField(
            model_name='limit',
            old_name='basic_domestic_needs_production',
            new_name='bdn_production',
        ),
        migrations.RemoveField(
            model_name='controlmeasure',
            name='basic_domestic_needs_allowed',
        ),
        migrations.RemoveField(
            model_name='controlmeasure',
            name='party',
        ),
        migrations.RemoveField(
            model_name='controlmeasure',
            name='production_allowed',
        ),
        migrations.RemoveField(
            model_name='controlmeasure',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='controlmeasure',
            name='limit_type',
            field=models.CharField(choices=[('Production', 'PRODUCTION'), ('Consumption', 'CONSUMPTION'), ('BDN', 'BDN')], default=1, help_text='Control measure types can be Production, Consumption and BDN', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='group',
            field=models.ForeignKey(help_text='Annex group', on_delete=django.db.models.deletion.PROTECT, related_name='control_measures', to='core.Group'),
        ),
        migrations.AddField(
            model_name='controlmeasure',
            name='party_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='control_measures', to='core.PartyType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlmeasure',
            name='baseline_type',
            field=models.ForeignKey(default=1, help_text='Baseline type', on_delete=django.db.models.deletion.PROTECT, related_name='control_measures', to='core.BaselineType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlmeasure',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlmeasure',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('baseline_type', models.ForeignKey(help_text='Baseline type', on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='core.BaselineType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='core.Group')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='core.Party')),
            ],
            options={
                'db_table': 'baseline',
            },
        ),
        migrations.RenameField(
            model_name='limit',
            old_name='bdn_production',
            new_name='limit',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='production',
        ),
        migrations.AddField(
            model_name='limit',
            name='limit_type',
            field=models.CharField(choices=[('Production', 'PRODUCTION'), ('Consumption', 'CONSUMPTION'), ('BDN', 'BDN')], default='', help_text='Control measure types can be Production, Consumption and BDN', max_length=64),
            preserve_default=False,
        ),
    ]
