# Generated by Django 2.1.4 on 2019-04-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20190329_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='gwp2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp_error_plus_minus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='number_of_isomers',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
