# Generated by Django 2.1.4 on 2019-04-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20190401_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='is_captured',
            field=models.BooleanField(default=False),
        ),
    ]
