# Generated by Django 2.1.4 on 2019-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_removing_essen_crit_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usestype',
            table='uses_type',
        ),
    ]
