# Generated by Django 2.1.4 on 2019-04-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_more_aggregation_fields'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='limit',
            table='limit_prod_cons',
        ),
        migrations.AlterModelTable(
            name='processagentemissionlimit',
            table='limit_pa_emission',
        ),
    ]
