# Generated by Django 2.1.4 on 2019-04-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_limits_table_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='other',
            field=models.BooleanField(default=False, help_text='Indicates whether this obligation is a main one. The main ones are: Article 7, Essential and Critical uses (RAF) and Transfer or addition of production or consumption.'),
        ),
        migrations.AlterField(
            model_name='submissionformat',
            name='is_default_party',
            field=models.BooleanField(default=False, help_text='Indicates whether this submission format is default for party.'),
        ),
    ]
