# Generated by Django 2.1.4 on 2019-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20190417_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_approved',
            field=models.NullBooleanField(default=None, help_text='If set to true it means that the nomination was approved.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_checked_blanks',
            field=models.BooleanField(default=True, verbose_name='Checked blanks'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_confirmed_blanks',
            field=models.BooleanField(default=False, verbose_name='Confirmed blanks'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_emergency',
            field=models.BooleanField(default=False, help_text='If set to true it means that ozone secretariat can fill out only the Approved form directly.', verbose_name='Emergency'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_blanks',
            field=models.BooleanField(default=False, verbose_name='Has blanks'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_a1',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex A Group 1 were reported.', verbose_name='Has reported A/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_a2',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex A Group 2 were reported.', verbose_name='Has reported A/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b1',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex B Group 1 were reported.', verbose_name='Has reported B/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b2',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex B Group 2 were reported.', verbose_name='Has reported B/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b3',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex B Group 3 were reported.', verbose_name='Has reported B/III'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c1',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex C Group 1 were reported.', verbose_name='Has reported C/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c2',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex C Group 2 were reported.', verbose_name='Has reported C/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c3',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex C Group 3 were reported.', verbose_name='Has reported C/III'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_e',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex E were reported.', verbose_name='Has reported E/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_f',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex F were reported.', verbose_name='Has reported F'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_provisional',
            field=models.BooleanField(default=False, help_text='If set to true it signals that future changes are foreseen.', verbose_name='Provisional'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_superseded',
            field=models.BooleanField(default=False, help_text='If set to true it means that the current version is not relevant anymore. When a newer version of data is Submitted, the current one is automatically flagged as Superseded.', verbose_name='Superseded'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_valid',
            field=models.NullBooleanField(default=None, help_text='If set to true it signals that the data in the current version is considered correct. Can be set by the Secretariat during Processing or at the transition between the Processing or Finalized states.', verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='other',
            field=models.BooleanField(default=False, help_text='Unset when this obligation is a main one. The main ones are: Article 7, Essential and Critical uses (RAF) and Transfer or addition of production or consumption.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_approved',
            field=models.NullBooleanField(default=None, help_text='If set to true it means that the nomination was approved.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_checked_blanks',
            field=models.BooleanField(default=True, verbose_name='Checked blanks'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_confirmed_blanks',
            field=models.BooleanField(default=False, verbose_name='Confirmed blanks'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_emergency',
            field=models.BooleanField(default=False, help_text='If set to true it means that ozone secretariat can fill out only the Approved form directly.', verbose_name='Emergency'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_blanks',
            field=models.BooleanField(default=False, verbose_name='Has blanks'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_a1',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex A Group 1 were reported.', verbose_name='Has reported A/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_a2',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex A Group 2 were reported.', verbose_name='Has reported A/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b1',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex B Group 1 were reported.', verbose_name='Has reported B/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b2',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex B Group 2 were reported.', verbose_name='Has reported B/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b3',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex B Group 3 were reported.', verbose_name='Has reported B/III'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c1',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex C Group 1 were reported.', verbose_name='Has reported C/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c2',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex C Group 2 were reported.', verbose_name='Has reported C/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c3',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex C Group 3 were reported.', verbose_name='Has reported C/III'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_e',
            field=models.BooleanField(default=True, help_text='If set to true it means that substances under Annex E were reported.', verbose_name='Has reported E/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_f',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex F were reported.', verbose_name='Has reported F'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_provisional',
            field=models.BooleanField(default=False, help_text='If set to true it signals that future changes are foreseen.', verbose_name='Provisional'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_superseded',
            field=models.BooleanField(default=False, help_text='If set to true it means that the current version is not relevant anymore. When a newer version of data is Submitted, the current one is automatically flagged as Superseded.', verbose_name='Superseded'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_valid',
            field=models.NullBooleanField(default=None, help_text='If set to true it signals that the data in the current version is considered correct. Can be set by the Secretariat during Processing or at the transition between the Processing or Finalized states.', verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='submissionformat',
            name='is_default_party',
            field=models.BooleanField(default=False, help_text='Indicates whether this submission format is default for party.', verbose_name='Is default for parties'),
        ),
    ]
