# Generated by Django 2.1.4 on 2019-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_add_fields_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcons',
            name='baseline_bdn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='baseline_cons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='baseline_prod',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
