# Generated by Django 2.1.4 on 2019-05-07 12:16

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_auto_20190423_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
    ]
