# Generated by Django 2.1.4 on 2019-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20190507_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='transfers_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Transfers remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='transfers_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Transfers remarks added by the ozone secretariat', max_length=9999),
        ),
    ]
