# Generated by Django 2.1.4 on 2019-05-10 12:42

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20190510_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalUseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Critical use categories',
                'db_table': 'critical_use_category',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='mdgregion',
            options={'ordering': ('name',), 'verbose_name': 'MDG Region'},
        ),
        migrations.AlterField(
            model_name='mdgregion',
            name='income_type',
            field=models.CharField(blank=True, choices=[('High', 'HIGH'), ('Low', 'LOW'), ('Lower-middle', 'LOWER_MIDDLE'), ('Upper-middle', 'UPPER_MIDDLE')], help_text='High, Low, Lower-middle, Upper-middle', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
    ]
