# Generated by Django 2.1.4 on 2019-05-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20190510_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_type',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='used_amount',
        ),
    ]
