# Generated by Django 2.1.4 on 2019-05-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20190510_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='gwp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
