# Generated by Django 2.1.4 on 2019-05-14 09:38

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20190513_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_a1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 1 were reported.', verbose_name='Has reported A/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_a2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 2 were reported.', verbose_name='Has reported A/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 1 were reported.', verbose_name='Has reported B/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 2 were reported.', verbose_name='Has reported B/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 3 were reported.', verbose_name='Has reported B/III'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 1 were reported.', verbose_name='Has reported C/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 2 were reported.', verbose_name='Has reported C/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 3 were reported.', verbose_name='Has reported C/III'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_e',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex E were reported.', verbose_name='Has reported E/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_a1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 1 were reported.', verbose_name='Has reported A/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_a2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 2 were reported.', verbose_name='Has reported A/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 1 were reported.', verbose_name='Has reported B/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 2 were reported.', verbose_name='Has reported B/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 3 were reported.', verbose_name='Has reported B/III'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 1 were reported.', verbose_name='Has reported C/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 2 were reported.', verbose_name='Has reported C/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 3 were reported.', verbose_name='Has reported C/III'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_e',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex E were reported.', verbose_name='Has reported E/I'),
        ),
    ]
