# Generated by Django 2.1.4 on 2019-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_auto_20190514_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rafreport',
            name='quantity_exempted',
        ),
    ]
