# Generated by Django 2.1.4 on 2019-05-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_compute_quantity_exempted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='ordering_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='remarks_os',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='remarks_party',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='submission',
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination_party_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='core.Submission'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core.ReportingPeriod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='source_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='core.Party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='source_party_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='core.Submission'),
        ),
    ]
