# Generated by Django 2.1.4 on 2019-05-16 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_auto_20190516_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcons',
            name='cons_transfer',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='prodconsmt',
            name='cons_transfer',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('P', 'Production'), ('C', 'Consumption')], max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obligation',
            name='_form_type',
            field=models.CharField(choices=[('art7', 'ART7'), ('essencrit', 'ESSENCRIT'), ('hat', 'HAT'), ('other', 'OTHER'), ('exemption', 'EXEMPTION'), ('transfer', 'TRANSFER')], help_text='Used to generate the correct form, based on this obligation.', max_length=64, null=True),
        ),
    ]
