# Generated by Django 2.1.4 on 2019-05-18 16:47

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20190516_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article7destruction',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AlterModelOptions(
            name='article7emission',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AlterModelOptions(
            name='article7export',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AlterModelOptions(
            name='article7import',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AlterModelOptions(
            name='article7nonpartytrade',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AlterModelOptions(
            name='article7production',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AlterModelOptions(
            name='highambienttemperatureimport',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AlterModelOptions(
            name='highambienttemperatureproduction',
            options={'ordering': ['ordering_id']},
        ),
        migrations.AddField(
            model_name='article7export',
            name='decision_polyols',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='article7import',
            name='decision_polyols',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
