# Generated by Django 2.1.4 on 2019-05-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_auto_20190518_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyhistory',
            name='population',
            field=models.IntegerField(),
        ),
    ]
