# Generated by Django 2.1.4 on 2019-05-20 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_auto_20190518_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafreport',
            name='quantity_exempted',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
