# Generated by Django 2.1.4 on 2019-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_quantity_exempted_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article7destruction',
            options={'ordering': ['substance__sort_order', 'substance__substance_id']},
        ),
        migrations.AlterModelOptions(
            name='article7export',
            options={'ordering': ['substance__sort_order', 'substance__substance_id', 'blend__sort_order']},
        ),
        migrations.AlterModelOptions(
            name='article7import',
            options={'ordering': ['substance__sort_order', 'substance__substance_id', 'blend__sort_order']},
        ),
        migrations.AlterModelOptions(
            name='article7nonpartytrade',
            options={'ordering': ['substance__sort_order', 'substance__substance_id', 'blend__sort_order']},
        ),
        migrations.AlterModelOptions(
            name='article7production',
            options={'ordering': ['substance__sort_order', 'substance__substance_id']},
        ),
        migrations.AlterModelOptions(
            name='highambienttemperatureimport',
            options={'ordering': ['substance__sort_order', 'substance__substance_id', 'blend__sort_order']},
        ),
        migrations.AlterModelOptions(
            name='highambienttemperatureproduction',
            options={'ordering': ['substance__sort_order', 'substance__substance_id']},
        ),
        migrations.AlterModelOptions(
            name='rafreport',
            options={'ordering': ['substance__sort_order', 'substance__substance_id']},
        ),
    ]
