# Generated by Django 2.1.4 on 2019-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_substance_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether reporting can be performed for this obligation.'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='has_reporting_periods',
            field=models.BooleanField(default=True, help_text='Indicates whether reporting is done periodically or upon certain events (e.g. transfers)'),
        ),
    ]
