# Generated by Django 2.1.4 on 2019-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_obligation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyhistory',
            name='population',
            field=models.IntegerField(),
        ),
    ]
