# Generated by Django 2.1.4 on 2019-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20190521_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='transfers_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Transfers remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AddField(
            model_name='submission',
            name='transfers_remarks_secretariat',
            field=models.CharField(blank=True, help_text='General Transfers remarks added by the ozone secretariat', max_length=9999),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption'), ('default_transfer', 'Default_transfer')], db_column='workflow_class', default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption'), ('default_transfer', 'Default_transfer')], db_column='workflow_class', default='empty', max_length=32),
        ),
    ]
