# Generated by Django 2.1.4 on 2019-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_transfers_remarks_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
