# Generated by Django 2.1.4 on 2019-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20190527_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissioninfo',
            name='country',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='country_fk',
            new_name='country',
        ),
    ]
