# Generated by Django 2.1.4 on 2019-05-29 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ozone.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_aggregations_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCriticalUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('critical_use_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_uses', to='core.CriticalUseCategory')),
                ('exemption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_uses', to='core.ExemptionApproved')),
            ],
            options={
                'db_table': 'exemption_approved_critical_use',
            },
        ),
        migrations.CreateModel(
            name='RAFReportUseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('critical_use_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_categories', to='core.CriticalUseCategory')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_categories', to='core.RAFReport')),
            ],
            options={
                'db_table': 'reporting_raf_use_category',
            },
            bases=(ozone.core.models.reporting.ModifyPreventionMixin, models.Model),
        ),
    ]
