# Generated by Django 2.1.4 on 2019-06-03 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20190530_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAgentUsesReported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=256)),
                ('process_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('makeup_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('emissions', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('units', models.CharField(blank=True, choices=[('MT', 'Metric Tonnes'), ('ODP', 'ODP Tonnes')], max_length=4, null=True)),
                ('remark', models.CharField(blank=True, max_length=9999)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_uses_reported', to='core.Submission')),
            ],
            options={
                'db_table': 'pa_uses_reported',
            },
        ),
        migrations.RemoveField(
            model_name='processagentcontaintechnology',
            name='party',
        ),
        migrations.RemoveField(
            model_name='processagentcontaintechnology',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='processagentcontaintechnology',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_contain_technologies', to='core.Submission'),
        ),
    ]
