# Generated by Django 2.1.4 on 2019-06-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20190603_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption'), ('default_transfer', 'Default_transfer'), ('default_process_agent', 'Default_process_agent')], db_column='workflow_class', default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='_form_type',
            field=models.CharField(choices=[('art7', 'ART7'), ('essencrit', 'ESSENCRIT'), ('hat', 'HAT'), ('other', 'OTHER'), ('exemption', 'EXEMPTION'), ('transfer', 'TRANSFER'), ('procagent', 'PROCAGENT')], help_text='Used to generate the correct form, based on this obligation.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption'), ('default_transfer', 'Default_transfer'), ('default_process_agent', 'Default_process_agent')], db_column='workflow_class', default='empty', max_length=32),
        ),
    ]
