# Generated by Django 2.1.4 on 2019-06-05 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_proc_agent_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processagentusesreported',
            name='emissions',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='processagentusesreported',
            name='makeup_quantity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='processagentusesreported',
            name='units',
            field=models.CharField(blank=True, choices=[('MT', 'Metric Tonnes'), ('ODP tonnes', 'ODP Tonnes')], max_length=64, null=True),
        ),
    ]
