# Generated by Django 2.1.4 on 2019-06-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20190605_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAgentEmissionLimitValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processagentemissionlimitvaliditys', to='core.Meeting')),
            ],
            options={
                'verbose_name_plural': 'process agent emission limits validity',
                'db_table': 'pa_emission_limit_validity',
            },
        ),
        migrations.CreateModel(
            name='ProcessAgentUsesValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processagentusesvaliditys', to='core.Meeting')),
            ],
            options={
                'verbose_name_plural': 'process agent uses validity',
                'db_table': 'pa_uses_validity',
            },
        ),
        migrations.RemoveField(
            model_name='decision',
            name='meeting',
        ),
        migrations.AlterModelOptions(
            name='processagentcontaintechnology',
            options={'verbose_name_plural': 'process agent contain technologies'},
        ),
        migrations.AlterModelOptions(
            name='processagentusesreported',
            options={'verbose_name_plural': 'process agent uses reported'},
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
    ]
