# Generated by Django 2.1.4 on 2019-06-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20190605_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='pa_contain_technology_remarks',
            new_name='pa_contain_technology_remarks_secretariat',
        ),
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='pa_uses_reported_remarks',
            new_name='pa_uses_reported_remarks_secretariat',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='pa_contain_technology_remarks',
            new_name='pa_contain_technology_remarks_secretariat',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='pa_uses_reported_remarks',
            new_name='pa_uses_reported_remarks_secretariat',
        ),
    ]
