# Generated by Django 2.1.4 on 2019-06-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_pa_remarks_secretariat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAgentEmissionLimitValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'process agent emission limits validity',
                'db_table': 'pa_emission_limit_validity',
            },
        ),
        migrations.CreateModel(
            name='ProcessAgentUsesValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'process agent uses validity',
                'db_table': 'pa_uses_validity',
            },
        ),
        migrations.AlterModelOptions(
            name='processagentcontaintechnology',
            options={'verbose_name_plural': 'process agent contain technologies'},
        ),
        migrations.AlterModelOptions(
            name='processagentusesreported',
            options={'verbose_name_plural': 'process agent uses reported'},
        ),
        migrations.RemoveField(
            model_name='processagentapplication',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='processagentemissionlimit',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='processagentusesreported',
            name='decision',
        ),
        migrations.AlterField(
            model_name='decision',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='processagentusesvalidity',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses_validity', to='core.Decision'),
        ),
        migrations.AddField(
            model_name='processagentemissionlimitvalidity',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits_validity', to='core.Decision'),
        ),
        migrations.AddField(
            model_name='processagentapplication',
            name='validity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_applications', to='core.ProcessAgentUsesValidity'),
        ),
        migrations.AddField(
            model_name='processagentemissionlimit',
            name='validity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_emission_limits', to='core.ProcessAgentEmissionLimitValidity'),
        ),
        migrations.AddField(
            model_name='processagentusesreported',
            name='validity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_uses_reported', to='core.ProcessAgentUsesValidity'),
        ),
    ]
