# Generated by Django 2.1.4 on 2019-06-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20190605_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processagentapplication',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_applications', to='core.ProcessAgentUsesValidity'),
        ),
        migrations.AlterField(
            model_name='processagentemissionlimit',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_emission_limits', to='core.ProcessAgentEmissionLimitValidity'),
        ),
        migrations.AlterField(
            model_name='processagentusesreported',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_uses_reported', to='core.ProcessAgentUsesValidity'),
        ),
    ]
