# Generated by Django 2.1.4 on 2019-06-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20190606_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processagentemissionlimitvalidity',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='limits_validity', to='core.Decision'),
        ),
        migrations.AlterField(
            model_name='processagentusesvalidity',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uses_validity', to='core.Decision'),
        ),
    ]
