# Generated by Django 2.1.4 on 2019-06-12 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20190606_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transferred_amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
