# Generated by Django 2.1.4 on 2019-06-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_transfer_amount_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='gwp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp_error_plus_minus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blend',
            name='cnumber',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='blend',
            name='composition_alt',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='blend',
            name='trade_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
