# Generated by Django 2.1.4 on 2019-06-12 15:47

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_gwp_float_blends'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='gwp_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
