# Generated by Django 2.1.4 on 2019-06-18 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_blend_substance_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='to_email',
        ),
        migrations.AddField(
            model_name='email',
            name='to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
