# Generated by Django 2.1.4 on 2019-06-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_auto_20190626_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processagentapplicationvalidity',
            options={'verbose_name_plural': 'process agent applications validity'},
        ),
        migrations.AlterField(
            model_name='processagentapplicationvalidity',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='applications_validity', to='core.Decision'),
        ),
        migrations.AlterModelTable(
            name='processagentapplicationvalidity',
            table='pa_applications_validity',
        ),
    ]
