# Generated by Django 2.1.4 on 2019-06-28 13:05

from django.db import migrations, models
import django.db.models.deletion
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_auto_20190626_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processagentcontaintechnology',
            old_name='contain_technology',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='processagentcontaintechnology',
            name='submission',
        ),
        migrations.AddField(
            model_name='processagentusesreported',
            name='contain_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pa_uses_reported', to='core.ProcessAgentContainTechnology'),
        ),
    ]
