# Generated by Django 2.1.4 on 2019-07-01 08:51

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20190628_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='pa_contain_technology_remarks_secretariat',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='pa_contain_technology_remarks_secretariat',
        ),
    ]
