# Generated by Django 2.1.4 on 2019-07-01 14:34

from django.db import migrations, models
import django.utils.timezone
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_deviation_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='core.Submission'),
        ),
        migrations.AlterModelOptions(
            name='criticalusecategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'critical use categories'},
        ),
        migrations.AlterModelOptions(
            name='mdgregion',
            options={'ordering': ('name',), 'verbose_name': 'MDG region'},
        ),
        migrations.AlterField(
            model_name='group',
            name='description_alt',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='alternate description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_alt',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='alternate name'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_checked_blanks',
            field=models.BooleanField(default=True, verbose_name='checked blanks'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_confirmed_blanks',
            field=models.BooleanField(default=False, verbose_name='confirmed blanks'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_blanks',
            field=models.BooleanField(default=False, verbose_name='has blanks'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_a1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 1 were reported.', verbose_name='has reported A/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_a2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 2 were reported.', verbose_name='has reported A/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 1 were reported.', verbose_name='has reported B/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 2 were reported.', verbose_name='has reported B/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_b3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 3 were reported.', verbose_name='has reported B/III'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 1 were reported.', verbose_name='has reported C/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 2 were reported.', verbose_name='has reported C/II'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_c3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 3 were reported.', verbose_name='has reported C/III'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_e',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex E were reported.', verbose_name='has reported E/I'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_has_reported_f',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex F were reported.', verbose_name='has reported F'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_provisional',
            field=models.BooleanField(default=False, help_text='If set to true it signals that future changes are foreseen.', verbose_name='provisional'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_superseded',
            field=models.BooleanField(default=False, help_text='If set to true it means that the current version is not relevant anymore. When a newer version of data is Submitted, the current one is automatically flagged as Superseded.', verbose_name='superseded'),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_valid',
            field=models.NullBooleanField(default=None, help_text='If set to true it signals that the data in the current version is considered correct. Can be set by the Secretariat during Processing or at the transition between the Processing or Finalized states.', verbose_name='valid'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_checked_blanks',
            field=models.BooleanField(default=True, verbose_name='checked blanks'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_confirmed_blanks',
            field=models.BooleanField(default=False, verbose_name='confirmed blanks'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_blanks',
            field=models.BooleanField(default=False, verbose_name='has blanks'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_a1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 1 were reported.', verbose_name='has reported A/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_a2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex A Group 2 were reported.', verbose_name='has reported A/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 1 were reported.', verbose_name='has reported B/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 2 were reported.', verbose_name='has reported B/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_b3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex B Group 3 were reported.', verbose_name='has reported B/III'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c1',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 1 were reported.', verbose_name='has reported C/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c2',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 2 were reported.', verbose_name='has reported C/II'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_c3',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex C Group 3 were reported.', verbose_name='has reported C/III'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_e',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex E were reported.', verbose_name='has reported E/I'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_has_reported_f',
            field=models.BooleanField(default=False, help_text='If set to true it means that substances under Annex F were reported.', verbose_name='has reported F'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_provisional',
            field=models.BooleanField(default=False, help_text='If set to true it signals that future changes are foreseen.', verbose_name='provisional'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_superseded',
            field=models.BooleanField(default=False, help_text='If set to true it means that the current version is not relevant anymore. When a newer version of data is Submitted, the current one is automatically flagged as Superseded.', verbose_name='superseded'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_valid',
            field=models.NullBooleanField(default=None, help_text='If set to true it signals that the data in the current version is considered correct. Can be set by the Secretariat during Processing or at the transition between the Processing or Finalized states.', verbose_name='valid'),
        ),
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
