# Generated by Django 2.1.4 on 2019-07-09 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_pluralization_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanOfAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('annex_group_description', models.CharField(blank=True, max_length=256, verbose_name=django.db.models.fields.CharField)),
                ('combined_id', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'plans_of_action',
                'db_table': 'plan_of_action',
            },
        ),
        migrations.CreateModel(
            name='PlanOfActionDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_adopted', models.PositiveIntegerField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Decision')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Party')),
            ],
            options={
                'db_table': 'plan_of_action_decision',
            },
        ),
        migrations.AddField(
            model_name='planofaction',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_of_action', to='core.PlanOfActionDecision'),
        ),
        migrations.AddField(
            model_name='planofaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_of_action', to='core.Group'),
        ),
        migrations.AddField(
            model_name='planofaction',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_of_action', to='core.Party'),
        ),
        migrations.AddField(
            model_name='planofaction',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_of_action', to='core.ReportingPeriod'),
        ),
        migrations.AlterUniqueTogether(
            name='planofaction',
            unique_together={('party', 'reporting_period', 'group')},
        ),
    ]
