# Generated by Django 2.1.4 on 2019-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_plan_of_action_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodcons',
            options={'verbose_name_plural': 'Production consumptions'},
        ),
        migrations.AlterModelOptions(
            name='prodconsmt',
            options={'verbose_name_plural': 'Production consumptions metric tonnes'},
        ),
    ]
