# Generated by Django 2.1.4 on 2019-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_pluralization_prodcons'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='sign_date_mp',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='sign_date_vc',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
