# Generated by Django 2.1.4 on 2019-07-31 08:18

from django.db import migrations, models
import django.db.models.deletion
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_party_declaration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedcriticaluse',
            options={'verbose_name_plural': 'Exemptions approved critical uses'},
        ),
        migrations.AlterModelOptions(
            name='exemptionapproved',
            options={'verbose_name_plural': 'Exemptions approved'},
        ),
        migrations.AlterField(
            model_name='approvedcriticaluse',
            name='exemption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_uses', to='core.ExemptionApproved'),
        ),
    ]
