# Generated by Django 2.1.4 on 2019-07-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_approvedcriticaluses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafreportusecategory',
            name='critical_use_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_categories', to='core.CriticalUseCategory'),
        ),
    ]
