# Generated by Django 2.1.4 on 2019-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_nullable_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planofaction',
            unique_together={('party', 'reporting_period', 'group', 'is_valid')},
        ),
    ]
