# Generated by Django 2.1.4 on 2019-08-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20190801_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ods', models.BooleanField(default=False)),
                ('date_reported_ods', models.DateField(null=True)),
                ('has_hfc', models.BooleanField(default=False)),
                ('date_reported_hfc', models.DateField(null=True)),
                ('remarks', models.CharField(blank=True, max_length=9999)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licensing_systems', to='core.Party')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licensing_systems', to='core.Submission')),
            ],
            options={
                'db_table': 'licensing_system',
            },
        ),
    ]
