# Generated by Django 2.1.4 on 2019-08-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_auto_20190806_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('reclaimed_substances', models.CharField(blank=True, max_length=512)),
                ('capacity', models.CharField(blank=True, max_length=64)),
                ('remarks', models.CharField(blank=True, max_length=9999)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_facilities', to='core.Party')),
            ],
            options={
                'verbose_name_plural': 'reclamation facilities',
                'db_table': 'reclamation_facility',
            },
        ),
    ]
