# Generated by Django 2.1.4 on 2019-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20190806_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligation',
            name='_form_type',
        ),
        migrations.AddField(
            model_name='obligation',
            name='_obligation_type',
            field=models.CharField(choices=[('art7', 'ART7'), ('essencrit', 'ESSENCRIT'), ('hat', 'HAT'), ('other', 'OTHER'), ('exemption', 'EXEMPTION'), ('transfer', 'TRANSFER'), ('procagent', 'PROCAGENT'), ('labuses', 'LABUSES'), ('art4b', 'ART4B'), ('art9', 'ART9'), ('reqchanges', 'REQCHANGES')], help_text='Used to generate the correct form and filter obligations.', max_length=64, null=True),
        ),
    ]
