# Generated by Django 2.1.4 on 2019-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20190808_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercountryprofiledata',
            name='url_type',
            field=models.CharField(choices=[('Submission', 'SUBMISSION'), ('Publication', 'PUBLICATION')], max_length=64, null=True),
        ),
    ]
