# Generated by Django 2.1.4 on 2019-08-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20190808_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='_obligation_type',
            field=models.CharField(choices=[('art7', 'ART7'), ('essencrit', 'ESSENCRIT'), ('hat', 'HAT'), ('other', 'OTHER'), ('exemption', 'EXEMPTION'), ('transfer', 'TRANSFER'), ('procagent', 'PROCAGENT'), ('labuses', 'LABUSES'), ('art4b', 'ART4B'), ('art9', 'ART9'), ('reqchanges', 'REQCHANGES'), ('odsstrategies', 'ODSSTRATEGIES'), ('unwantedimports', 'UNWANTEDIMPORTS')], help_text='Used to generate the correct form and filter obligations.', max_length=64, null=True),
        ),
    ]
