# Generated by Django 2.1.4 on 2019-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20190808_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ormreport',
            options={'verbose_name': 'ORM report'},
        ),
    ]
