# Generated by Django 2.1.4 on 2019-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20190812_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilateralfund',
            name='last_updated',
            field=models.DateField(null=True),
        ),
    ]
