# Generated by Django 2.1.4 on 2019-08-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_auto_20190813_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='time_reported_f',
            field=models.DateTimeField(help_text='Date at which substances under Annex F were reported.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_reported_f',
            field=models.DateTimeField(help_text='Date at which substances under Annex F were reported.', null=True),
        ),
    ]
