# Generated by Django 2.1.4 on 2019-08-14 07:44

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_time_reported_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='time_reported_f',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time_reported_f',
        ),
        migrations.AddField(
            model_name='historicalsubmission',
            name='date_reported_f',
            field=models.DateField(help_text='Date at which substances under Annex F were reported.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='date_reported_f',
            field=models.DateField(help_text='Date at which substances under Annex F were reported.', null=True),
        ),
    ]
