# Generated by Django 2.1.4 on 2019-08-15 13:19

from django.db import migrations


def move_nomination_filled_to_processing(apps, schema_editor):
    Submission = apps.get_model('core', 'Submission')
    for exemption_sub in Submission.objects.filter(
        _current_state='nomination_filled'
    ):
        exemption_sub._current_state = 'processing'
        exemption_sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_date_reported_f'),
    ]

    operations = [
        migrations.RunPython(move_nomination_filled_to_processing),
    ]
