# Generated by Django 2.1.4 on 2019-08-15 14:55

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_exemptions_processing_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focalpoint',
            options={'ordering': ('ordering_id',)},
        ),
        migrations.AlterModelOptions(
            name='illegaltrade',
            options={'ordering': ('ordering_id',)},
        ),
    ]
