# Generated by Django 2.1.4 on 2019-08-15 16:18

from django.db import migrations


def move_accelerated_to_default(apps, schema_editor):
    Submission = apps.get_model('core', 'Submission')
    Submission.objects.filter(
        _workflow_class='accelerated_exemption'
    ).update(
        _workflow_class='default_exemption'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_focal_points_illegal_trade_ordering'),
    ]

    operations = [
        migrations.RunPython(move_accelerated_to_default, elidable=True),
    ]
