# Generated by Django 2.1.4 on 2019-08-15 16:42

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_remove_acc_exemption_wf_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubmission',
            name='flag_approved',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='flag_approved',
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
    ]
