# Generated by Django 2.1.4 on 2019-08-20 14:25

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_remove_acc_exemption_wf_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilateralfund',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='multilateralfund',
            name='date_approved',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='multilateralfund',
            name='date_disbursed',
            field=models.DateField(null=True),
        ),
    ]
