# Generated by Django 2.1.4 on 2019-08-15 16:18

from django.db import migrations


def replace_eu_code(apps, schema_editor):
    Party = apps.get_model('core', 'Party')
    Party.objects.filter(
        abbr='ECE'
    ).update(
        abbr='EU'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_mlf_dates'),
    ]

    operations = [
        migrations.RunPython(replace_eu_code),
    ]
