# Generated by Django 2.1.4 on 2019-08-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_ECE_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the party can submit new reports.Only necessary for backwards compatibility'),
        ),
    ]
