# Generated by Django 2.1.4 on 2019-08-29 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_remove_exemption_flag_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedcriticaluse',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7destruction',
            name='quantity_destroyed',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='quantity_captured_all_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='quantity_captured_feedstock',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='quantity_captured_for_destruction',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='quantity_destroyed',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='quantity_emitted',
            field=models.DecimalField(decimal_places=15, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='quantity_feedstock',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7emission',
            name='quantity_generated',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_critical_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_essential_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_feedstock',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_high_ambient_temperature',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_laboratory_analytical_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_other_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_polyols',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_process_agent_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_quarantine_pre_shipment',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_total_new',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7export',
            name='quantity_total_recovered',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_critical_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_essential_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_feedstock',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_high_ambient_temperature',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_laboratory_analytical_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_other_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_polyols',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_process_agent_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_quarantine_pre_shipment',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_total_new',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7import',
            name='quantity_total_recovered',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='quantity_export_new',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='quantity_export_recovered',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='quantity_import_new',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7nonpartytrade',
            name='quantity_import_recovered',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_article_5',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_critical_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_essential_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_feedstock',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_for_destruction',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_high_ambient_temperature',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_laboratory_analytical_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_other_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_process_agent_uses',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_quarantine_pre_shipment',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='article7production',
            name='quantity_total_produced',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='baseline',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='blend',
            name='gwp',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='blend',
            name='odp',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='blendcomponent',
            name='percentage',
            field=models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='controlmeasure',
            name='allowed',
            field=models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='deviationsource',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='deviationsource',
            name='production',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='exemptionapproved',
            name='approved_teap_amount',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='exemptionapproved',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_dcpac',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Used in ducted commercial packaged air conditioners', max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_msac',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Used in multi-split air conditioners', max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureimport',
            name='quantity_sdac',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Used in split ducted air conditioners', max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_dcpac',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Used in ducted commercial packaged air conditioners', max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_msac',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Used in multi-split air conditioners', max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='highambienttemperatureproduction',
            name='quantity_sdac',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Used in split ducted air conditioners', max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='limit',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='planofaction',
            name='benchmark',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='processagentemissionlimit',
            name='makeup_consumption',
            field=models.DecimalField(decimal_places=15, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='processagentemissionlimit',
            name='max_emissions',
            field=models.DecimalField(decimal_places=15, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='processagentusesreported',
            name='emissions',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='processagentusesreported',
            name='makeup_quantity',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='baseline_bdn',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='baseline_cons',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='baseline_prod',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='calculated_consumption',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='calculated_production',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='cons_transfer',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='destroyed',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='export_essential_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='export_feedstock',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='export_new',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='export_process_agent',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='export_quarantine',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='export_recovered',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='import_essential_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='import_feedstock',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='import_laboratory_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='import_new',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='import_process_agent',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='import_quarantine',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='import_recovered',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='limit_bdn',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='limit_cons',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='limit_prod',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='non_party_export',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='non_party_import',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='prod_transfer',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='production_all_new',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='production_article_5',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='production_essential_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='production_feedstock',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='production_laboratory_analytical_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='production_process_agent',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodcons',
            name='production_quarantine',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='calculated_consumption',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='calculated_production',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='cons_transfer',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='destroyed',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='export_essential_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='export_feedstock',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='export_new',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='export_process_agent',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='export_quarantine',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='export_recovered',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='import_essential_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='import_feedstock',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='import_laboratory_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='import_new',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='import_process_agent',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='import_quarantine',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='import_recovered',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='non_party_export',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='non_party_import',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='prod_transfer',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='production_all_new',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='production_article_5',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='production_essential_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='production_feedstock',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='production_laboratory_analytical_uses',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='production_process_agent',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='prodconsmt',
            name='production_quarantine',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafimport',
            name='quantity',
            field=models.DecimalField(decimal_places=15, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafreport',
            name='on_hand_start_year',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafreport',
            name='quantity_destroyed',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafreport',
            name='quantity_exempted',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafreport',
            name='quantity_exported',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafreport',
            name='quantity_production',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafreport',
            name='quantity_used',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rafreportusecategory',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp_baseline',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='gwp_error_plus_minus',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='max_odp',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='substance',
            name='min_odp',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='substance',
            name='odp',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transferred_amount',
            field=models.DecimalField(decimal_places=15, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
