# Generated by Django 2.1.4 on 2019-09-13 06:11

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_licensing_system_files_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='flag_checked_blanks',
            field=models.BooleanField(default=False, verbose_name='checked blanks'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag_checked_blanks',
            field=models.BooleanField(default=False, verbose_name='checked blanks'),
        ),
    ]
