# Generated by Django 2.1.4 on 2019-09-17 09:19

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_checked_blanks_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensingsystem',
            name='date_reported_hfc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensingsystem',
            name='date_reported_ods',
            field=models.DateField(blank=True, null=True),
        ),
    ]
