# Generated by Django 2.1.4 on 2019-09-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_licensing_system_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Only custom blends will be associated with a Party.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_blends', to='core.Party'),
        ),
    ]
