# Generated by Django 2.1.4 on 2019-09-20 08:55

from django.db import migrations


def populate_prodcons_flags(apps, schema_editor):
    """
    Populates is_eu_member and is_article5 flags for existing ProdCons entries.
    """
    ProdCons = apps.get_model('core', 'ProdCons')
    ProdConsMT = apps.get_model('core', 'ProdConsMT')
    PartyHistory = apps.get_model('core', 'PartyHistory')

    for party, rp in ProdConsMT.objects.all().values_list(
        'party', 'reporting_period'
    ):
        ph = PartyHistory.objects.filter(
            party=party, reporting_period=rp
        ).first()
        if ph:
            ProdCons.objects.filter(
                party=party, reporting_period=rp
            ).update(is_article5=ph.is_article5, is_eu_member=ph.is_eu_member)
            ProdConsMT.objects.filter(
                party=party, reporting_period=rp
            ).update(is_article5=ph.is_article5, is_eu_member=ph.is_eu_member)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_prodcons_party_flags'),
    ]

    operations = [
        migrations.RunPython(populate_prodcons_flags),
    ]
