# Generated by Django 2.1.4 on 2019-09-20 15:13

from django.db import migrations


def populate_prodcons_flags(apps, schema_editor):
    """
    Populates is_eu_member and is_article5 flags for existing ProdCons entries.
    """
    ProdCons = apps.get_model('core', 'ProdCons')
    ProdConsMT = apps.get_model('core', 'ProdConsMT')
    PartyHistory = apps.get_model('core', 'PartyHistory')

    for party, rp, is_article5, is_eu_member in PartyHistory.objects.all().values_list(
        'party', 'reporting_period', 'is_article5', 'is_eu_member'
    ):
        ProdCons.objects.filter(
            party=party, reporting_period=rp
        ).update(is_article5=is_article5, is_eu_member=is_eu_member)
        ProdConsMT.objects.filter(
            party=party, reporting_period=rp
        ).update(is_article5=is_article5, is_eu_member=is_eu_member)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_populate_new_prodcons_flags'),
    ]

    operations = [
        migrations.RunPython(populate_prodcons_flags)
    ]
