# Generated by Django 2.1.4 on 2019-09-23 15:23

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_truly_properly_populate_prodcons_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensingsystemfile',
            name='title',
            field=models.CharField(default='-', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licensingsystemurl',
            name='title',
            field=models.CharField(default='-', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licensingsystemfile',
            name='file',
            field=models.FileField(upload_to='licensing-system/'),
        ),
        migrations.AlterField(
            model_name='othercountryprofiledata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='other-country-profile-data/'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
        migrations.AlterField(
            model_name='website',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='website/'),
        ),
    ]
