# Generated by Django 2.1.4 on 2019-09-24 09:00

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_auto_20190923_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcons',
            name='calculated_laboratory_consumption',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='prodcons',
            name='calculated_laboratory_production',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='prodcons',
            name='calculated_qps_consumption',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='prodcons',
            name='calculated_qps_production',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='prodconsmt',
            name='calculated_laboratory_consumption',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='prodconsmt',
            name='calculated_laboratory_production',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='prodconsmt',
            name='calculated_qps_consumption',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='prodconsmt',
            name='calculated_qps_production',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=25, null=True),
        ),
    ]
