# Generated by Django 2.1.4 on 2019-09-24 14:40

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_aggregation_qps_lab_calculations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensingsystemfile',
            name='file',
            field=models.FileField(upload_to='public/licensing-system/'),
        ),
        migrations.AlterField(
            model_name='othercountryprofiledata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='public/other-country-profile-data/'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.file.SubmissionFile.get_storage_directory),
        ),
        migrations.AlterField(
            model_name='website',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='public/website/'),
        ),
    ]
