# Generated by Django 2.1.4 on 2019-09-24 15:25

from django.db import migrations, models
import ozone.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_aggregation_qps_lab_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemptionapproved',
            name='is_article5',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='exemptionapproved',
            name='is_eu_member',
            field=models.NullBooleanField(),
        ),
    ]
