# Generated by Django 2.1.4 on 2019-09-24 15:50

from django.db import migrations


def populate_prodcons_flags(apps, schema_editor):
    """
    Populates is_eu_member and is_article5 flags for existing ProdCons entries.
    """
    ExemptionApproved = apps.get_model('core', 'ExemptionApproved')
    PartyHistory = apps.get_model('core', 'PartyHistory')

    for party, rp, is_article5, is_eu_member in PartyHistory.objects.all().values_list(
        'party', 'reporting_period', 'is_article5', 'is_eu_member'
    ):
        ExemptionApproved.objects.filter(
            submission__party=party, submission__reporting_period=rp
        ).update(is_article5=is_article5, is_eu_member=is_eu_member)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_exemptionapproved_eu_article5_flags'),
    ]

    operations = [
        migrations.RunPython(populate_prodcons_flags, elidable=True),
    ]
